export const SET_GOAL = "SET_GOAL";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOAD_FIT_DAY_START = "LOAD_FIT_DAY_START";
export const LOAD_FIT_DAY_SUCCESS = "LOAD_FIT_DAY_SUCCESS";
export const LOAD_FIT_DAY_FAILURE = "LOAD_FIT_DAY_FAILURE";

export const LOAD_FIT_WEEK_START = "LOAD_FIT_WEEK_START";
export const LOAD_FIT_WEEK_SUCCESS = "LOAD_FIT_WEEK_SUCCESS";
export const LOAD_FIT_WEEK_FAILURE = "LOAD_FIT_WEEK_FAILURE";

export const LOAD_FIT_MONTH_START = "LOAD_FIT_MONTH_START";
export const LOAD_FIT_MONTH_SUCCESS = "LOAD_FIT_MONTH_SUCCESS";
export const LOAD_FIT_MONTH_FAILURE = "LOAD_FIT_MONTH_FAILURE";

export const LOAD_FIT_DATA_START = "LOAD_FIT_DATA_START";
export const LOAD_FIT_DATA_SUCCESS = "LOAD_FIT_DATA_SUCCESS";
export const LOAD_FIT_DATA_FAILURE = "LOAD_FIT_DATA_FAILURE";
