export const SET_GOAL = "SET_GOAL";
export const LOAD_FIT_WEEK_START = "LOAD_FIT_WEEK_START";
export const LOAD_FIT_WEEK_SUCCESS = "LOAD_FIT_WEEK_SUCCESS";
export const LOAD_FIT_WEEK_FAILURE = "LOAD_FIT_WEEK_FAILURE";
export const LOAD_FIT_MONTH_START = "LOAD_FIT_MONTH_START";
export const LOAD_FIT_MONTH_SUCCESS = "LOAD_FIT_MONTH_SUCCESS";
export const LOAD_FIT_MONTH_FAILURE = "LOAD_FIT_MONTH_FAILURE";
